[project]
name = "baker_demo"
default = "merge_test"

[env.output]
dir = "release"

[env.version]
source = "file"
file = "version.h"
template = """
#define VERSION_MAJOR  ${MAJOR}
#define VERSION_MINOR  ${MINOR}
#define VERSION_PATCH  ${PATCH}
#define BUILD_NUMBER   ${BUILD}
"""

[bootloaders.default]
file = "build/bt.hex"
base_addr = 0x0800_0000
app_offset = 0x8000

# custom header definiton
[headers.custom_fpk]
suffix = "fpk"
def = """
@endian = little;

struct header @packed {
    magic:          [u8; 4] = @bytes("fpk");
    config:         u32 = 0;
    old_version:    [u8; 16];
    new_version:    [u8; 16] = [${VER.MAJOR}, ${VER.MINOR}, ${VER.PATCH}];
    watermark:      [u8; 16] = @bytes("baker");
    partition:      [u8; 16] = @bytes("app");
    img_size:       u32 = @sizeof(image);
    packed_size:    u32 = @sizeof(image);
    timestamp:      u32 = ${TIME.EPOCH32};
    img_crc32:      u32 = @crc32(image);
    packed_crc32:   u32 = @crc32(image);
    header_crc32:   u32 = @crc32(@self[..header_crc32]);
    _padding:       [u8; 1024 - @offsetof(_padding)];
}
"""

[targets.merge_test]
type = "merge"
description = "Merge bootloader and app"
bootloader = "default"
app_file = "build/app.hex"
output_format = "hex"  # use bin if not specified
output_name = "${PROJECT}_v${VER.MAJOR}.${VER.MINOR}.${VER.PATCH}_build.${VER.BUILD}_${DATE}"

[targets.pack_bin]
type = "pack"
description = "Pack with custom header"
header = "custom_fpk"  # use custom header
app_file = "build/app.bin"
app_offset = 0x8000  # needed if app is binary
output_name = "${PROJECT}_v${VER.MAJOR}.${VER.MINOR}.${VER.PATCH}"

[targets.convert_bin]
type = "convert"
description = "Convert hex to bin"
input_file = "build/app.hex"
output_format = "bin"
output_name = "converted_bin"

[targets.convert_srec]
type = "convert"
description = "Convert to S-record format"
input_file = "build/app.hex"
output_format = "srec"
output_name = "converted_srec"