use std::fs;
use std::path::PathBuf;
use log::debug;
use srec::{Address32, Count24, Record};
use crate::firmware::FirmwareError;
use crate::firmware::{Image, ImageReader, ImageWriter};

pub struct SrecReader {
    file: PathBuf,
}

pub struct SrecWriter {
    file: PathBuf,
}

impl SrecReader {
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { file: path.into() }
    }
}

impl SrecWriter {
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { file: path.into() }
    }
}

impl ImageReader for SrecReader {
    fn read(&self) -> Result<Image, FirmwareError> {
        let s = fs::read_to_string(&self.file)?;
        let records = srec::read_records(&s);
        let mut image = Image::new();

        for record in records {
            let record = record?;
            match record {
                srec::Record::S0(s) => debug!("S0 header: \"{}\"", s),
                srec::Record::S1(data) => image.add_data(data.address.into(), data.data), 
                srec::Record::S2(data) => image.add_data(data.address.into(), data.data),
                srec::Record::S3(data) => image.add_data(data.address.into(), data.data),
                _ => {}  // s5/6 record count and s7/8/9 are ignored
            }
        }

        Ok(image)
    }
}

impl ImageWriter for SrecWriter {
    fn write(&self, image: &Image) -> Result<(), FirmwareError> {
        let records = build_records(image)?;
        let s = srec::generate_srec_file(&records);
        std::fs::write(&self.file, &s)?;
        Ok(())
    }
}

fn build_records(image: &Image) -> Result<Vec<srec::Record>, FirmwareError> {
    let mut records = Vec::new();
    let ver = env!("CARGO_PKG_VERSION");
    records.push(Record::S0(format!("baker_v{}", ver)));

    const MAX_DATA_SIZE: usize = 32; // SREC recommended chunk size

    let mut data_record_count = 0;
    for (start_addr, data) in image.segments() {
        let mut addr = *start_addr;
        for chunk in data.chunks(MAX_DATA_SIZE) {
            records.push(Record::S3(srec::Data {
                address: Address32(addr),
                data: chunk.to_vec(),
            }));
            addr += chunk.len() as u32;
            data_record_count += 1;
        }
    }
    
    // Add record count (optional but recommended)
    records.push(Record::S6(Count24(data_record_count)));
    
    records.push(Record::S7(Address32(0)));
    Ok(records)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;
    use std::io::Write;

    #[test]
    fn test_read_srec() {
        // Hand-crafted SREC with correct checksums (generated by srec crate)
        let srec_content = "\
S00F000062616B65725F76302E322E3028
S31608000000010203040506070809000A0B0C0D0E0F1059
S604000001FA
S70500000000FA
";
        let mut file = NamedTempFile::new().unwrap();
        file.write_all(srec_content.as_bytes()).unwrap();
        
        let reader = SrecReader::new(file.path());
        let image = reader.read().unwrap();
        
        // Verify the data was read correctly
        assert_eq!(image.data_size(), 17);
        assert_eq!(image.address_range(), Some((0x08000000, 0x08000010)));
        
        // Verify actual data content
        let segments: Vec<_> = image.segments().iter().collect();
        assert_eq!(segments.len(), 1);
        let (addr, data) = segments[0];
        assert_eq!(*addr, 0x08000000);
        assert_eq!(data, &[0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 
                           0x09, 0x00, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]);
    }

    #[test]
    fn test_write_srec() {
        let mut image = Image::new();
        image.add_data(0x08000000, vec![0x01, 0x02, 0x03, 0x04]);
        
        let file = NamedTempFile::new().unwrap();
        let writer = SrecWriter::new(file.path());
        writer.write(&image).unwrap();
        
        let content = std::fs::read_to_string(file.path()).unwrap();
        assert!(content.starts_with("S0"));
        assert!(content.contains("S3"));
        assert!(content.contains("S7"));
    }

    #[test]
    fn test_roundtrip() {
        let mut image = Image::new();
        image.add_data(0x08000000, vec![0xAA; 100]); // Large data to test chunking
        
        let file = NamedTempFile::new().unwrap();
        let writer = SrecWriter::new(file.path());
        writer.write(&image).unwrap();
        
        let reader = SrecReader::new(file.path());
        let image2 = reader.read().unwrap();
        
        assert_eq!(image.data_size(), image2.data_size());
        assert_eq!(image.address_range(), image2.address_range());
    }

    #[test]
    #[ignore]
    fn generate_valid_srec_for_testing() {
        // Helper test to generate valid SREC with correct checksums
        let mut image = Image::new();
        image.add_data(0x08000000, vec![0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 
                                        0x09, 0x00, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]);
        
        let file = NamedTempFile::new().unwrap();
        let writer = SrecWriter::new(file.path());
        writer.write(&image).unwrap();
        
        let content = std::fs::read_to_string(file.path()).unwrap();
        println!("Generated SREC content:");
        println!("{}", content);
    }

    #[test]
    fn test_chunking_large_data() {
        let mut image = Image::new();
        image.add_data(0x1000, vec![0xFF; 128]); // Larger than MAX_DATA_SIZE
        
        let records = build_records(&image).unwrap();
        
        // Should have: S0 + multiple S3 + S5 + S7
        let s3_count = records.iter().filter(|r| matches!(r, Record::S3(_))).count();
        assert!(s3_count > 1, "Large data should be split into multiple records");
    }
}
